const signUpTypesActions  = {
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_RESET: 'SIGNUP_START',

    SIGNUP_OTP_START: 'SIGNUP_OTP_START',
    SIGNUP_OTP_SUCCESS: 'SIGNUP_OTP_SUCCESS',
    SIGNUP_OTP_FAILURE: 'SIGNUP_OTP_FAILURE',
    SIGNUP_OTP_RESET: 'SIGNUP_OTP_START',

    SIGNUP_AVN_START: 'SIGNUP_AVN_START',
    SIGNUP_AVN_SUCCESS: 'SIGNUP_AVN_SUCCESS',
    SIGNUP_AVN_FAILURE: 'SIGNUP_AVN_FAILURE',
    SIGNUP_AVN_RESET: 'SIGNUP_AVN_START',
};
export default signUpTypesActions;